if [[ -s "${HOME}/.settings/commands/package-install.zsh" ]]; then
    source "${HOME}/.settings/commands/package-install.zsh"
fi

if [[ -s "${HOME}/.zprofile" ]]; then
    source "${HOME}/.zprofile"
fi
