if [[ -s "${HOME}/.settings/commands/package-install.zsh" ]]; then
    source "${HOME}/.settings/commands/package-install.zsh"
fi

if [[ -s "${HOME}/.settings/zsh/aliases.zsh" ]]; then
    source "${HOME}/.settings/zsh/aliases.zsh"
fi

if [[ -s "${HOME}/.settings/zsh/exports.zsh" ]]; then
    source "${HOME}/.settings/zsh/exports.zsh"
fi

if [[ -s "${HOME}/.settings/zsh/settings.zsh" ]]; then
    source "${HOME}/.settings/zsh/settings.zsh"
fi
